import random

print("Please guess which integer will be generated by the matrix, between 1 and 20: ")
val = input ()


random_number = random.randint(1,20)

print("The number is " + str(random_number))

if val == random_number:
    print("YOU WON!!!")
elif val < random_number:
    print("Your guess was too low.")
else:
    print("Your guess was too high.")
    